name: Build and Publish VSCode Extension

on:
  push:
    tags:
      - 'v*.*.*' # Matches version tags like v1.1.1

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Set version from tag
      run: |
        TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\/v//')
        jq --arg version "$TAG" '.version = $version' package.json > package.tmp.json
        mv package.tmp.json package.json

    - name: Lint and build
      run: npm run build

    - name: Package extension
      run: |
        npm install -g @vscode/vsce
        vsce package

    - name: Publish to VSCode Marketplace
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
      run: vsce publish -p $VSCE_PAT